### ISSUE TITLE
Performance on TinyImageNet

### ISSUE THREAD

**Issue by ShiWuxuan** [dipamgoswami/FeCAM#3]
Hi,
Thanks for sharing the code of your nice work!
We are running experiments with it and rying to reproduce the results in the paper. 
Is the given file “FeCAM_tinyimagenet.json” the correct configuration? We get far less results on TinyImageNet than in the paper. 
Also we noticed that on TinyImageNet the training image is cropped to 32×32 while the test image is cropped to 56×56, is there any error here?

Thank you!

**Comment by dipamgoswami** [comment]
Hi @ShiWuxuan, 
The given file “FeCAM_tinyimagenet.json” is the correct configuration, and you should be able to reproduce the same results as in the paper using the available code. The trained weights from the initial step are also available for reproducing the results.

I retrained using the same code, and I am able to exactly reproduce the results.

Regarding the image size, it is not an error. While some previous methods resized the training images to 224\*224 resolution, in order to be able to use Resnet18, it is computationally very expensive and the training process is very slow. So, we train with the image size of 32\*32 and use the modified resnet (which is used for 32\*32 image size as in CIFAR100), which is quite fast and yields even better results compared to training with 224\*224 image sizes. For the test images, we follow the same transforms that are commonly used.

We also have results with training 224\*224 size images (see the TinyImageNet column) as follows:
![Screenshot from 2023-12-24 20-29-07](https://github.com/dipamgoswami/FeCAM/assets/40790714/cf1b2cd4-2c74-4fb1-a8cd-c002c67a7608)

Note that we also re-implement FeTrIL with the same setting as FeCAM and we get better results on FeTrIL as well by training with 32\*32 cropped images.

**Comment by ShiWuxuan** [comment]
Hi Dipam,
Thank you for your quick and detailed reply!
I successfully reproduced the results from the paper using the provided code as well as the initial weights. The reason for this issue is that the PyCIL framework does not provide an official implementation of TinyImageNet dataset loading, and my local TinyImageNet structure does not match the dataset implementation in this repository.
Thanks!
