### ISSUE TITLE
Storage cost of saving covariance matrices

### ISSUE THREAD

**Issue by BlacknoSheep** [dipamgoswami/FeCAM#4]
If a 512x512 covariance matrix is saved for each class, will the required storage space exceed that needed to save all feature vectors (512x500)?

**Comment by dipamgoswami** [comment]
Hi,
In case of CIFAR100 dataset, yes. It will require marginally less storage space to save all feature vectors instead of saving covariance matrices. However, for big datasets like ImageNet100, there are 1300 feature vectors corresponding to training images for each class. Hence, as a general solution, it is favourable to store the covariance matrices.
